### ISSUE TITLE
investspec tests are failing

### ISSUE THREAD

**Issue by emlys** [natcap/invest.users-guide#119]
investspec tests are failing because the output RST does not have the expected structure:
```
======================================================================
ERROR: test_invest_spec (test.test_investspec.TestInvestSpec)
invest_spec role function should return what sphinx expects.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/emily/invest.users-guide/extensions/investspec/test/test_investspec.py", line 56, in test_invest_spec
    nodes, messages = investspec.invest_spec(
  File "/Users/emily/invest.users-guide/extensions/investspec/investspec.py", line 89, in invest_spec
    return parse_rst(rst), []
  File "/Users/emily/invest.users-guide/extensions/investspec/investspec.py", line 33, in parse_rst
    return list(first_node.findall(descend=False, siblings=True))
AttributeError: 'target' object has no attribute 'findall'

======================================================================
ERROR: test_parse_rst (test.test_investspec.TestInvestSpec)
parse_rst should create a correct list of docutils nodes.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/emily/invest.users-guide/extensions/investspec/test/test_investspec.py", line 29, in test_parse_rst
    nodes = investspec.parse_rst(
  File "/Users/emily/invest.users-guide/extensions/investspec/investspec.py", line 33, in parse_rst
    return list(first_node.findall(descend=False, siblings=True))
AttributeError: 'paragraph' object has no attribute 'findall'
```
This does not seem related to recent changes, I can reproduce it locally with the 3.12.1 version of the `invest.users-guide` and `invest`. There have not been any recent releases of sphinx or docutils either.

**Comment by dcdenu4** [comment]
I think this was fixed in https://github.com/natcap/invest.users-guide/pull/120
